#It is used when to want to give self built errors or if the API is not working
#eg.
a=4
try:
     if a<3:
            print("hello")
except:
        print("there is something wrong")
